name: deploy easy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.20.1]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install pnpm@7.14.1 -g
        pnpm install
        pnpm run build
  
  
    - name: SCP Command to Transfer Files
      # You may pin to the exact commit or the version.
      # uses: appleboy/scp-action@6d1fc191a822daa12faa45f3a985413f995ff5c5
      uses: appleboy/scp-action@v0.1.3
      with:
        # scp remote host
        host: ${{ secrets.TENCENT_CLOUD_HOST }}
        # scp remote port
        port: 22
        # scp username
        username: ${{ secrets.TENCENT_CLOUD_USER }}
        # scp password
        password: ${{ secrets.TENCENT_CLOUD_PASS }}
        # target path on the server
        target: "/root/web/easy"
        # scp file list
        source: "dist/*"
        # remove target folder before upload data
        rm: true

